### PR TITLE
added ability to Merge and Copy bloom filters

### PR DESCRIPTION
**Pull request by Newbrict**

### CODE REVIEW

**Comment by Newbrict** [comment]
[plant: bloom]$ go fmt                                                                                        :)
[plant: bloom]$ go test                                                                                       :)
PASS
ok  	bloom	18.746s

**Comment by Newbrict** [comment]
Any feedback? Why not merge?

**Comment by willf** [comment]
Sorry, I’ve been very busy. Will hope to review/merge this week.

-- 
Will


On November 14, 2015 at 11:20:56 AM, Dimitar Dimitrov (notifications@github.com) wrote:

Any feedback? Why not merge?

**Comment by willf** [comment]
Thanks!

**Pull request merged**
